### ISSUE TITLE
About Us

### ISSUE THREAD

**Issue by dnavarez** [NavarezCorp/prenda#20]
<h1>What is Prenda?</h1>

"Prenda" is a Bisaya term which now a days commonly found in a Pawnshop store. In other words "Pawn". Item's are pawned on pawnshop store and if owners no longer wants to redeemed their items, it will expire and pawnshop store will have the authority to auction the item.

<h4>And what's special about Prenda?</h4> 

If you haven't noticed how great this online site is, <b>ITEM</b>'s came from a <b>PAWNSHOP</b> store. Which means, items have undergone a <b>scrutiny</b> and <b>meticulous</b> inspection before it is being approved.

<h4>How good is that for me?</h4>

It would mean that you have a good quality item. Quality gold, quality watches and many more. Not like the usual online seller whom you don't know and some's are scammer. Those kind of sellers are headaches to online seller sites cause they had no idea of the sellers. It degrades dignity and security on the sites. And they'd keep trying on how to prevent and fight it for the good of the buyer.

Unlike Prenda, you are guaranteed that they belong to a legit Pawnshop store. And because of this, if there are problems, you know where to reach out or return the item. Unlike others, all you can do is shout out to social media and then still nothing. We do this cause we <b>CARE</b> for you.

<h4>Customer Service</h4>

For any questions, suggestion or feedback, please contact us <a href="Contact Us">here<a> and we will try our best to respond to your inquiry within 24 hours. We will be glad to hear from you.

**Comment by pnavarez** [comment]
done
