### ISSUE TITLE
Distorted image on Home page

### ISSUE THREAD

**Issue by dnavarez** [NavarezCorp/prenda#27]
Apply style to image so that it will not distorted
max-width:100%;
max-height:100%;

<img width="388" alt="screen shot 2016-03-24 at 8 49 33 pm" src="https://cloud.githubusercontent.com/assets/1557918/14017392/0f7c1ae2-f202-11e5-9b66-7b10ac7d4895.png">

**Comment by pnavarez** [comment]
done
